#
# The values has to be in base64 format
#
apiVersion: v1
kind: Secret
metadata:
  name: secret-#{deployment_name}#
  namespace: #{namespace}#
stringData:
  GITHUB_TOKEN: "#{GITHUB_TOKEN}#"
  AZURE_DEVOPS_PAT: "#{AZURE_DEVOPS_PAT}#"
  BEREAN_MAX_RULES_CHARS: "#{BEREAN_MAX_RULES_CHARS}#"
  BEREAN_HOST: "#{BEREAN_HOST}#"
  BEREAN_PORT: "#{BEREAN_PORT}#"
  BEREAN_DEFAULT_LANGUAGE: "#{BEREAN_DEFAULT_LANGUAGE}#"
  BEREAN_DEFAULT_MODEL: "#{BEREAN_DEFAULT_MODEL}#"
  BEREAN_FALLBACK_MODEL: "#{BEREAN_FALLBACK_MODEL}#"
  BEREAN_OLLAMA_ENDPOINT: "#{BEREAN_OLLAMA_ENDPOINT}#"
  BEREAN_OLLAMA_API_KEY: "#{BEREAN_OLLAMA_API_KEY}#"
