import { isAuthenticated } from '../../services/copilot-auth.js';
import {
  addReviewedCommitsTag,
  addReviewedIterationTag,
  shouldIgnorePR,
  type SourceControlPort,
} from '../ports/source-control.port.js';
import {
  resolveSourceControlFromUrl,
  resolveSourceControlFromFlags,
} from '../../infrastructure/source-control/source-control-registry.js';
import { getBuiltInRulesPath, parseRuleSources, resolveRules } from '../../services/rules.js';
import { getModelMaxRulesChars } from '../../services/model-limits.js';
import type { ReviewIssue, ReviewResult } from '../ports/review-model.port.js';
import {
  generateProviderRuleQueries,
  reviewWithSelectedProvider,
  stopProviders,
} from '../../providers/provider-registry.js';
import { extractErrorMessage } from '../../lib/errors.js';
import type { ConfigPort } from '../ports/config.port.js';
import { getEnvConfig } from '../../infrastructure/config/env-config.repository.js';

export interface ReviewPullRequestInput {
  url?: string;
  owner?: string;
  org?: string;
  project?: string;
  repo?: string;
  pr?: string;
  model?: string;
  language?: string;
  postComment?: boolean;
  inline?: boolean;
  skipIfReviewed?: boolean;
  incremental?: boolean;
  force?: boolean;
  confidenceThreshold?: number | string;
  rules?: string;
  skipFolders?: string;
  verbose?: boolean;
  config?: ConfigPort;
  onProgress?: (event: { phase: string; message: string }) => void;
}

type ExistingReview = {
  threadId: number;
  commentId: number;
  reviewedIterationId?: number;
  content: string;
};

export type ReviewPullRequestResult =
  | { status: 'failed'; error: string }
  | { status: 'skipped'; reason: string }
  | {
      status: 'completed';
      reviewResult: ReviewResult;
      postFailed: boolean;
    };

function progress(input: ReviewPullRequestInput, phase: string, message: string): void {
  input.onProgress?.({ phase, message });
}

function formatReviewAsMarkdown(reviewResult: ReviewResult): string {
  let md = '## 🔍 AI Code Review\n\n';

  if (reviewResult.summary) {
    md += `### Summary\n${reviewResult.summary}\n\n`;
  }

  if (reviewResult.recommendation) {
    const recEmoji: Record<string, string> = {
      APPROVE: '✅',
      APPROVE_WITH_SUGGESTIONS: '✅💡',
      NEEDS_CHANGES: '⚠️',
      NEEDS_DISCUSSION: '💬',
    };
    const emoji = recEmoji[reviewResult.recommendation] || '📋';
    md += `### ${emoji} Recommendation: ${reviewResult.recommendation.replace(/_/g, ' ')}\n\n`;
  }

  if (reviewResult.issues && reviewResult.issues.length > 0) {
    md += '### Issues Found\n\n';
    md += formatIssuesGroupedByFile(reviewResult.issues);
  } else if (!reviewResult.summary && reviewResult.review) {
    const reviewText = reviewResult.review.trim();
    if (reviewText.startsWith('{') || reviewText.includes('"summary"') || reviewText.includes('"issues"')) {
      md += reviewResult.review + '\n\n';
    } else {
      md += '⚠️ **Review could not be parsed.** The AI model returned a non-structured response. Please re-run the review.\n\n';
    }
  } else {
    md += '✅ **No issues found!** Code looks good.\n\n';
  }

  if (reviewResult.positives && reviewResult.positives.length > 0) {
    md += '### ✅ Good Practices\n';
    for (const positive of reviewResult.positives) {
      md += `- ${positive}\n`;
    }
    md += '\n';
  }

  if (reviewResult.recommendations && reviewResult.recommendations.length > 0) {
    md += '### 💡 Recommendations\n';
    for (const rec of reviewResult.recommendations) {
      md += `- ${rec}\n`;
    }
    md += '\n';
  }

  md += '\n---\n*Generated by [Berean](https://github.com/iatecbr/IATec.AI.WorkFlow.Review.Berean) 🔍*';
  return md;
}

function formatIssuesGroupedByFile(issues: ReviewIssue[]): string {
  const byFile = new Map<string, ReviewIssue[]>();
  const general: ReviewIssue[] = [];

  for (const issue of issues) {
    if (issue.file) {
      if (!byFile.has(issue.file)) byFile.set(issue.file, []);
      byFile.get(issue.file)?.push(issue);
    } else {
      general.push(issue);
    }
  }

  let md = '';
  for (const [file, fileIssues] of byFile) {
    md += `#### \`${file}\`\n\n`;
    for (const issue of fileIssues) {
      md += renderIssueMarkdown(issue);
    }
  }

  if (general.length > 0) {
    if (byFile.size > 0) md += '#### General\n\n';
    for (const issue of general) {
      md += renderIssueMarkdown(issue);
    }
  }

  return md;
}

function renderIssueMarkdown(issue: ReviewIssue): string {
  const icon = issue.severity === 'critical' ? '🔴' : issue.severity === 'warning' ? '🟡' : '🔵';
  let md = `${icon} **${issue.severity.toUpperCase()}**`;
  if (issue.category) md += ` [${issue.category}]`;
  if (issue.confidence) md += ` (${issue.confidence}%)`;
  if (issue.line) md += ` — linha ${issue.line}`;
  md += '\n';
  if (issue.title) md += `**${issue.title}**\n`;
  md += `${issue.message}\n`;
  if (issue.suggestion) {
    md += `\n\`\`\`suggestion\n${issue.suggestion}\n\`\`\`\n`;
  }
  md += '\n';
  return md;
}

function formatIssueAsMarkdown(issue: ReviewIssue): string {
  const icon = issue.severity === 'critical' ? '🔴' : issue.severity === 'warning' ? '🟡' : '🔵';
  let md = `${icon} **${issue.severity.toUpperCase()}**`;
  if (issue.category) md += ` [${issue.category}]`;
  if (issue.confidence) md += ` (${issue.confidence}%)`;
  md += '\n';
  if (issue.title) md += `**${issue.title}**\n`;
  md += issue.message;
  if (issue.suggestion) {
    md += `\n\n\`\`\`suggestion\n${issue.suggestion}\n\`\`\``;
  }
  return md;
}

function buildIncrementalComment(newContent: string, previousContent: string): string {
  const cleanPrevious = previousContent
    .replace(/<!-- berean-review -->/g, '')
    .replace(/<!-- berean-commits:.*?:berean-commits -->/gs, '')
    .replace(/<!-- berean-iteration:\d+:berean-iteration -->/g, '')
    .trim();

  const timestamp = new Date().toISOString().split('T')[0];

  return (
    `${newContent}\n\n` +
    `<details>\n<summary>📜 Previous review (${timestamp})</summary>\n\n${cleanPrevious}\n\n</details>`
  );
}

async function postGeneralComment(
  provider: SourceControlPort,
  reviewResult: ReviewResult,
  commitIds: string[] = [],
  currentIterationId: number | undefined,
  existingReview: ExistingReview | null = null,
  incremental = false,
): Promise<boolean> {
  let newComment = formatReviewAsMarkdown(reviewResult);

  if (commitIds.length > 0) {
    newComment = addReviewedCommitsTag(newComment, commitIds);
  }
  if (currentIterationId) {
    newComment = addReviewedIterationTag(newComment, currentIterationId);
  }

  if (incremental && existingReview) {
    const fullComment = buildIncrementalComment(newComment, existingReview.content);
    const result = await provider.updatePRComment(existingReview.threadId, existingReview.commentId, fullComment);
    return result.success;
  }

  const result = await provider.postPRComment(newComment);
  return result.success;
}

async function postInlineIssues(provider: SourceControlPort, reviewResult: ReviewResult): Promise<boolean> {
  const inlineIssues = (reviewResult.issues ?? []).filter(i => i.file && i.line);
  if (inlineIssues.length === 0) {
    return true;
  }

  const comments = inlineIssues.map(issue => ({
    filePath: issue.file!,
    line: issue.line!,
    content: formatIssueAsMarkdown(issue),
  }));

  const result = await provider.postInlineComments(comments);
  return result.failed === 0;
}

export async function reviewPullRequest(input: ReviewPullRequestInput): Promise<ReviewPullRequestResult> {
  try {
    if (input.verbose) {
      process.env.BEREAN_VERBOSE = '1';
    }

    if (!isAuthenticated()) {
      return { status: 'failed', error: 'Not authenticated. Run: berean auth login' };
    }

    progress(input, 'resolve-provider', 'Resolving PR provider...');
    const resolveResult = input.url
      ? resolveSourceControlFromUrl(input.url)
      : resolveSourceControlFromFlags(input);

    if (!resolveResult.adapter) {
      return { status: 'failed', error: resolveResult.error ?? 'Could not resolve PR provider' };
    }

    const provider = resolveResult.adapter;

    progress(input, 'fetch-pr-info', 'Fetching PR info...');
    const prBasicInfo = await provider.fetchPRBasicInfo();
    if (!prBasicInfo.success || !prBasicInfo.prDetails) {
      return { status: 'failed', error: prBasicInfo.error ?? 'Failed to fetch PR info' };
    }

    if (!input.force && shouldIgnorePR(prBasicInfo.prDetails.description)) {
      return { status: 'skipped', reason: 'PR description contains @berean: ignore' };
    }

    let existingReview: ExistingReview | null = null;
    let reviewedCommits: string[] = [];
    let allCommits: string[] = [];
    let newCommits: string[] = [];
    let fromIterationId: number | undefined;
    let previousCommitId: string | undefined;

    if (input.skipIfReviewed || input.incremental) {
      progress(input, 'check-existing-reviews', 'Checking for existing reviews...');
      const [bereanComments, prCommits] = await Promise.all([
        provider.findBereanComments(),
        provider.getPRCommits(),
      ]);

      allCommits = prCommits;
      if (bereanComments.length > 0) {
        const latest = bereanComments[bereanComments.length - 1];
        existingReview = {
          threadId: latest.threadId,
          commentId: latest.commentId,
          reviewedIterationId: latest.reviewedIterationId,
          content: latest.content,
        };
        reviewedCommits = latest.reviewedCommits ?? [];
        if (reviewedCommits.length > 0) {
          previousCommitId = reviewedCommits[reviewedCommits.length - 1];
        }

        newCommits = allCommits.filter(c => !reviewedCommits.includes(c));
        if (input.skipIfReviewed && newCommits.length === 0) {
          return { status: 'skipped', reason: 'PR already reviewed by Berean (no new commits)' };
        }
        if (input.incremental && newCommits.length === 0) {
          return { status: 'skipped', reason: 'No new commits since last review' };
        }
        if ((input.incremental || input.skipIfReviewed) && existingReview.reviewedIterationId) {
          fromIterationId = existingReview.reviewedIterationId;
        }
      }
    } else {
      allCommits = await provider.getPRCommits();
    }

    progress(input, 'fetch-diff', 'Fetching PR diff...');
    const skipFolders = input.skipFolders
      ? input.skipFolders.split(',').map(folder => folder.trim()).filter(Boolean)
      : [];

    const diffResult = await provider.fetchPRDiff({
      fromIterationId,
      newCommitIds: newCommits.length > 0 ? newCommits : undefined,
      previousCommitId,
      skipFolders,
    });

    if (!diffResult.success || !diffResult.diff) {
      return { status: 'failed', error: diffResult.error ?? 'Failed to fetch PR diff' };
    }

    const language = input.language || getDefaultLanguage();
    const model = input.model || getDefaultModel();
    let rules: string | undefined;
    const userRulesInput = input.rules || getRulesPath();

    function getDefaultLanguage(): string { return (input.config ?? getEnvConfig()).get('defaultLanguage') ?? 'English'; }
    function getDefaultModel(): string { return (input.config ?? getEnvConfig()).get('defaultModel') ?? 'gpt-4o'; }
    function getRulesPath(): string | undefined { return (input.config ?? getEnvConfig()).get('rulesPath'); }
    function getFallbackModel(): string | undefined { return (input.config ?? getEnvConfig()).get('fallbackModel'); }
    const builtInRulesPath = getBuiltInRulesPath();
    const rulesInput = userRulesInput ? `${builtInRulesPath},${userRulesInput}` : builtInRulesPath;

    progress(input, 'load-rules', 'Loading project rules...');
    try {
      const sources = parseRuleSources(rulesInput);
      const maxRulesCharsDefault = await getModelMaxRulesChars(model);
      const rulesResult = await resolveRules(
        sources,
        diffResult.diff,
        (diff) => generateProviderRuleQueries(diff, model),
        maxRulesCharsDefault,
      );
      rules = rulesResult.rules || undefined;
    } catch {
      rules = undefined;
    }

    progress(input, 'review', `Reviewing with ${model}...`);
    const confidenceThreshold = typeof input.confidenceThreshold === 'string'
      ? parseInt(input.confidenceThreshold, 10)
      : input.confidenceThreshold;

    const reviewResult = await reviewWithSelectedProvider(diffResult.diff, {
      model,
      language,
      rules,
      confidenceThreshold,
      fallbackModel: getFallbackModel(),
      onFallback: (fallbackModel, reason) => {
        progress(input, 'review-fallback', `Primary model failed (${reason}). Retrying with fallback model "${fallbackModel}"...`);
      },
    });

    if (!reviewResult.success) {
      return { status: 'failed', error: reviewResult.error ?? 'Review failed' };
    }

    let postFailed = false;
    if (input.inline) {
      progress(input, 'post-inline', 'Posting inline comments...');
      const success = await postInlineIssues(provider, reviewResult);
      if (!success) {
        postFailed = true;
      }
    }

    if (input.postComment) {
      progress(input, 'post-comment', 'Posting review comment...');
      const success = await postGeneralComment(
        provider,
        reviewResult,
        allCommits,
        diffResult.currentIterationId,
        existingReview,
        input.incremental,
      );
      if (!success) {
        postFailed = true;
      }
    }

    progress(input, 'complete', 'Review complete!');
    return { status: 'completed', reviewResult, postFailed };
  } catch (error) {
    const message = extractErrorMessage(error);
    return { status: 'failed', error: message };
  } finally {
    await stopProviders();
  }
}